[tool.poetry]
name = "tango_process_markdown"
version = "0.1.0"
description = ""
authors = ["Johannes Schmidt <johannes.schmidt.vik@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/johschmidt42/tango-process-markdown"
repository = "https://github.com/johschmidt42/tango-process-markdown"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.7.0"
httpx = "^0.23.3"
pyperclip = "^1.8.2"

[tool.poetry.group.lint.dependencies]
black = "^22.12.0"
isort = "^5.11.4"
flake8 = "^6.0.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
